In [1]:
from pathlib import Path

Path.cwd()

WindowsPath('c:/Users/Mesut/Desktop/kfz-insurance-risk-platform/notebooks')

In [2]:
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent
RAW_DATA_DIR = PROJECT_ROOT / "data" / "raw"

FREQUENCY_FILE = RAW_DATA_DIR / "freMTPL2freq.pq"
SEVERITY_FILE = RAW_DATA_DIR / "freMTPL2sev.pq"

print("Proje ana klasörü:", PROJECT_ROOT)
print("Frequency dosyası:", FREQUENCY_FILE)
print("Severity dosyası:", SEVERITY_FILE)

Proje ana klasörü: c:\Users\Mesut\Desktop\kfz-insurance-risk-platform
Frequency dosyası: c:\Users\Mesut\Desktop\kfz-insurance-risk-platform\data\raw\freMTPL2freq.pq
Severity dosyası: c:\Users\Mesut\Desktop\kfz-insurance-risk-platform\data\raw\freMTPL2sev.pq

In [3]:
print("Frequency mevcut mu?", FREQUENCY_FILE.exists())
print("Severity mevcut mu?", SEVERITY_FILE.exists())

Frequency mevcut mu? True
Severity mevcut mu? True

In [4]:
import pandas as pd

frequency_df = pd.read_parquet(
    FREQUENCY_FILE,
    engine="fastparquet"
)

frequency_df.head()

,IDpol,ClaimNb,Exposure,Area,VehPower,VehAge,DrivAge,BonusMalus,VehBrand,VehGas,Density,Region
0,1.0,1,0.10,D,5,0,55,50,B12,Regular,1217.0,R82
1,3.0,1,0.77,D,5,0,55,50,B12,Regular,1217.0,R82
2,5.0,1,0.75,B,6,2,52,50,B12,Diesel,54.0,R22
3,10.0,1,0.09,B,7,0,46,50,B12,Diesel,76.0,R72
4,11.0,1,0.84,B,7,0,46,50,B12,Diesel,76.0,R72

In [5]:
frequency_df.shape

(678013, 12)

In [6]:
severity_df = pd.read_parquet(
    SEVERITY_FILE,
    engine="fastparquet"
)

severity_df.head()

       IDpol  ClaimAmount
0     1552.0       995.20
1  1010996.0      1128.12
2  4024277.0      1851.11
3  4007252.0      1204.00
4  4046424.0      1204.00

In [7]:
severity_df.shape

(26639, 2)